'from data_ingestion.ear_polymarket import get_ear_feature'  
'import numpy as np'  
'vals = []'  
'for i in range(10):'  
'    feat = get_ear_feature()'  
'    if feat:'  
'        vals.append(feat["prob"])'  
'print("Ear v4 values:", vals)'  
'if vals:'  
'    print("Mean:", np.mean(vals))'  
'    print("Std:", np.std(vals))'  
'    print("Min:", np.min(vals))'  
'    print("Max:", np.max(vals))' 
