from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB_SRC = ROOT / "web" / "src"


def _read(relative_path: str) -> str:
    return (WEB_SRC / relative_path).read_text(encoding="utf-8")


def test_app_redirects_backtest_to_lab_and_keeps_current_nav_items():
    source = _read("App.tsx")
    assert "React.lazy(() => import('./pages/Dashboard'))" in source
    assert "React.lazy(() => import('./pages/Senses'))" in source
    assert "React.lazy(() => import('./pages/StrategyLab'))" in source
    assert "React.lazy(() => import('./pages/ExecutionConsole'))" in source
    assert "<React.Suspense" in source
    assert "頁面載入中" in source
    assert "{ to: '/execution', label: '⚡ 實戰交易' }" in source
    assert "{ to: '/lab', label: '🧪 策略實驗室' }" in source
    assert '<Route path="/execution" element={<ExecutionConsole />} />' in source
    assert '<Route path="/backtest" element={<Navigate to="/lab" replace />} />' in source
    assert "📊 儀表板" in source

def test_execution_console_consumes_runtime_status_and_exposes_operations_vs_diagnostics_split():
    source = _read("pages/ExecutionConsole.tsx")
    required_snippets = [
        'const { data: runtimeStatus, loading, error, refresh: refreshRuntimeStatus } = useApi<ExecutionConsoleRuntimeStatusResponse>("/api/status", 60000);',
        'const { data: executionOverview, loading: overviewLoading, error: overviewError, refresh: refreshExecutionOverview } = useApi<ExecutionOverviewResponse>("/api/execution/overview", 60000);',
        'const { data: executionRuns, loading: runsLoading, error: runsError, refresh: refreshExecutionRuns } = useApi<ExecutionRunsResponse>("/api/execution/runs", 60000);',
        'const handleRunAction = async (endpoint: string, pendingLabel: string, successLabel: string) => {',
        'const [operatorActionState, setOperatorActionState] = useState<{ tone: "idle" | "pending" | "success" | "error"; message: string }>({',
        'const executionSurfaceContract = runtimeStatus?.execution_surface_contract ?? null;',
        'const operationsSurface = executionSurfaceContract?.operations_surface ?? null;',
        'const diagnosticsSurface = executionSurfaceContract?.diagnostics_surface ?? null;',
        'const liveRuntimeTruth = runtimeStatus?.execution?.live_runtime_truth ?? executionSurfaceContract?.live_runtime_truth ?? null;',
        'const liveRouting = liveRuntimeTruth?.sleeve_routing ?? null;',
        'const automationEnabled = Boolean(runtimeStatus?.automation);',
        'const executionSymbol = runtimeStatus?.symbol || "BTCUSDT";',
        'const handleOperatorTrade = async (side: "buy" | "reduce") => {',
        'const handleAutomationToggle = async (enabled: boolean) => {',
        'executionReconciliation?.recovery_state?.status',
        'Execution Console / 實戰交易',
        'operations surface',
        'diagnostics surface',
        'Sleeve routing / bot activation',
        'Guardrail / blocker',
        'Capital / account snapshot',
        'Bot profiles / capital preview',
        'Capital allocation preview',
        'stateful run lifecycle 已落地',
        'planned budget',
        'start contract',
        'routing reason',
        'start reason',
        'operator run state',
        'event log',
        'shared-symbol runtime mirror',
        'binding summary',
        'ownership boundary',
        'capital preview source',
        'shared balance total',
        'preview positions',
        'preview open orders',
        'reconciliation status',
        'last live order',
        'operator action',
        '建立 run / resume',
        '暫停 run',
        '停止 run',
        'Stateful run lifecycle',
        'latest event',
        'next operator action',
        'Recovery / reconciliation',
        'Metadata / venue readiness',
        '最近委託 / reject / failure',
        'Manual operator controls',
        'fetchApi<any>("/api/trade", {',
        'fetchApi<{ automation?: boolean; message?: string }>("/api/automation/toggle", {',
        'automation {automationEnabled ? "ON" : "off"}',
        '買入 0.001 BTC',
        '減碼 0.001 BTC',
        '切到手動模式',
        '切到自動模式',
        '手動交易 controls 與 automation toggle 已搬到這頁；Dashboard 保留 guardrail / recovery diagnostics，per-bot capital ledger / capital actions 仍未完成。',
        '前往 Dashboard 診斷 →',
        '前往 Strategy Lab 挑策略 →',
        'Execution Console 現在直接消費同一份 runtime sleeve routing；真正缺的不是再做一套規則，而是把 bot profile/run lifecycle 與資金配置接上這份 activation truth。',
    ]
    for snippet in required_snippets:
        assert snippet in source


def test_dashboard_keeps_live_decision_quality_and_execution_guardrails_surfaces():
    source = _read("pages/Dashboard.tsx")
    required_snippets = [
        '<ConfidenceIndicator',
        'decisionQualityScore={confidenceData.decision_quality_score}',
        'expectedDrawdownPenalty={confidenceData.expected_drawdown_penalty}',
        'expectedTimeUnderwater={confidenceData.expected_time_underwater}',
        'allowedLayers={confidenceData.allowed_layers}',
        'deploymentBlocker={confidenceData.deployment_blocker}',
        'deploymentBlockerDetails={confidenceData.deployment_blocker_details}',
        'supportProgress={confidenceData.support_progress}',
        'currentLiveStructureBucket={confidenceData.current_live_structure_bucket ?? confidenceData.structure_bucket}',
        'floorCrossVerdict={confidenceData.floor_cross_verdict}',
        'bestSingleComponent={confidenceData.best_single_component}',
        'componentExperimentVerdict={confidenceData.component_experiment_verdict}',
        'q15ExactSupportedComponentPatchApplied={confidenceData.q15_exact_supported_component_patch_applied}',
        'const { data: runtimeStatus, refresh: refreshRuntimeStatus } = useApi<RuntimeStatusResponse>("/api/status", 60000);',
        'await refreshRuntimeStatus();',
        'const executionSurfaceContract = runtimeStatus?.execution_surface_contract ?? null;',
        'const executionOperationsSurface = executionSurfaceContract?.operations_surface ?? null;',
        'const executionDiagnosticsSurface = executionSurfaceContract?.diagnostics_surface ?? null;',
        'const executionReconciliation = runtimeStatus?.execution_reconciliation ?? null;',
        'const liveRecentPathologyApplied = Boolean(',
        'const liveRecentPathologyReason =',
        'const liveRecentPathologyWindow =',
        'const liveRecentPathologyAlerts =',
        'const liveRecentPathologySummary =',
        'const deploymentBlockerDetails = confidenceData?.deployment_blocker_details ?? null;',
        'const breakerRecentWindow = deploymentBlockerDetails?.recent_window ?? null;',
        'const breakerRelease = deploymentBlockerDetails?.release_condition ?? null;',
        'const circuitBreakerActive = confidenceData?.deployment_blocker === "circuit_breaker_active";',
        'const reconciliationLifecycleContract = executionReconciliation?.lifecycle_contract ?? null;',
        'const reconciliationArtifactChecklist = Array.isArray(reconciliationLifecycleContract?.artifact_checklist)',
        'const reconciliationVenueLanes = Array.isArray(reconciliationLifecycleContract?.venue_lanes)',
        'getLifecycleChecklistTone',
        'const metadataSmoke = runtimeStatus?.execution_metadata_smoke ?? null;',
        'const lastRejectContext = lastReject?.context ?? null;',
        'const lastRejectRuleLines = formatGuardrailRules(lastRejectContext?.rules);',
        '手動交易即時回饋',
        'normalized qty',
        'normalized price',
        'Metadata smoke 摘要',
        'public metadata contract 驗證通過',
        'smoke freshness',
        'artifact age',
        'stale/unavailable policy 已啟用',
        'getSmokeFreshnessTone',
        'getSmokeFreshnessLabel',
        'getSmokeGovernanceTone',
        'const metadataSmokeFreshness = metadataSmoke?.freshness ?? null;',
        'const metadataSmokeGovernance = metadataSmoke?.governance ?? null;',
        'const metadataSmokeAutoRefresh = metadataSmokeGovernance?.auto_refresh ?? null;',
        'const metadataSmokeBackgroundMonitor = metadataSmokeGovernance?.background_monitor ?? null;',
        'const metadataSmokeExternalMonitor = metadataSmokeGovernance?.external_monitor ?? null;',
        'const externalMonitorInstallContract = metadataSmokeExternalMonitor?.install_contract ?? null;',
        'const externalMonitorTickingState = metadataSmokeExternalMonitor?.ticking_state ?? null;',
        'getExternalMonitorTickingTone',
        'external monitor state',
        'observed-ticking',
        'installed-but-not-ticking',
        'stale governance',
        'auto refresh',
        'background monitor',
        'external monitor',
        'refresh command:',
        'external monitor command:',
        'preferred host lane:',
        'install status',
        'active lane',
        'install checked at:',
        'install command:',
        'install verify:',
        'crontab verify stdout:',
        'fallback contract:',
        'fallback command:',
        'systemd user timer:',
        'escalation:',
        'execution route contract',
        'canonical route {executionSurfaceContract.canonical_execution_route ?? "unknown"}',
        'canonical surface {executionSurfaceContract.canonical_surface_label ?? "Dashboard / Execution 狀態面板"}',
        'shortcut lane {executionSurfaceContract.shortcut_surface?.name ?? "signal_banner"}',
        'operations surface {executionOperationsSurface?.label || "Execution Console / 實戰交易"}',
        'diagnostics surface {executionDiagnosticsSurface?.label || "Dashboard / Execution 狀態面板"}',
        'executionOperationsSurface?.message',
        'Execution Console 升級前提：{executionOperationsSurface.upgrade_prerequisite}',
        '前往 Execution Console →',
        'executionSurfaceContract.shortcut_surface.message',
        '升級前提：{executionSurfaceContract.shortcut_surface.upgrade_prerequisite}',
        'readiness scope {executionSurfaceContract.readiness_scope ?? "runtime_governance_visibility_only"}',
        'executionSurfaceContract.operator_message',
        'live blockers:',
        'Guardrail context 面板',
        'raw → adjusted → delta → rules',
        'const guardrails = executionSummary?.guardrails ?? null;',
        'const positions = Array.isArray(accountSummary?.positions) ? accountSummary.positions : [];',
        'const openOrders = Array.isArray(accountSummary?.open_orders) ? accountSummary.open_orders : [];',
        'const accountRequestedSymbol = accountSummary?.requested_symbol ?? null;',
        'const accountNormalizedSymbol = accountSummary?.normalized_symbol ?? null;',
        'const accountCapturedAt = accountSummary?.captured_at ?? null;',
        'const accountDegraded = Boolean(accountSummary?.degraded);',
        'const accountOperatorMessage = accountSummary?.operator_message ?? null;',
        'const accountRecoveryHint = accountSummary?.recovery_hint ?? null;',
        'Execution runtime truth / detail',
        'Recent distribution pathology',
        'window {liveRecentPathologyWindow ?? "—"} rows',
        'reason {liveRecentPathologyReason || "—"}',
        'alerts {(liveRecentPathologyAlerts || []).join(" / ") || "none"}',
        '這代表最近 canonical 決策樣本正在退化；operator 應先看 drift / regime concentration，而不是把暫時高分當成可部署容量。',
        'support alignment',
        'runtime exact support',
        'calibration exact lane',
        'runtime 已有',
        'raw reason {liveRuntimeTruth.allowed_layers_raw_reason || "—"}',
        'final reason {liveRuntimeTruth.allowed_layers_reason || "—"}',
        'circuit breaker：recent 50 release window',
        '至少還差 {breakerWinsGap ?? "—"} 勝',
        '目前主 blocker 是 recent win rate，不是 q15 patch。',
        '不要把 support / component patch 當成 breaker release 替代品。',
        'Dashboard 只應同步 release math，不可把 q15 patch active / support-ready 包裝成 deployment readiness。',
        'Recovery / operator next step',
        'Execution reconciliation / recovery',
        'snapshot freshness',
        'trade history',
        'open-order audit',
        'lifecycle stage {reconciliationLifecycleAudit?.stage || "unknown"}',
        'restart replay {reconciliationLifecycleAudit?.restart_replay_required ? "required" : "not-required"}',
        'baseline contract {reconciliationLifecycleContract?.baseline_contract_status || "unknown"}',
        'replay verdict {reconciliationLifecycleContract?.replay_verdict || "unknown"}',
        'artifact coverage {reconciliationLifecycleContract?.artifact_coverage || "unknown"}',
        'Snapshot / symbol scope',
        'Trade history audit',
        'Open-order audit',
        'Lifecycle / replay audit',
        'runtime → history {reconciliationLifecycleAudit?.runtime_state || "—"} → {reconciliationLifecycleAudit?.trade_history_state || "—"}',
        'operator action {reconciliationRecoveryState?.operator_action || reconciliationLifecycleAudit?.operator_action || "先檢查 Dashboard execution runtime surface。"}',
        'replay verdict summary {reconciliationLifecycleContract?.replay_verdict_summary || "—"}',
        'missing lifecycle events {(reconciliationLifecycleContract?.missing_event_types || []).join(" / ") || "none"}',
        'Artifact checklist / per-order closure',
        'artifact checklist summary {reconciliationLifecycleContract?.artifact_checklist_summary || "—"}',
        'artifact provenance {reconciliationLifecycleContract?.artifact_provenance_summary || "—"}',
        '逐筆 order artifact 對帳：validation → ack → trade history → partial fill / cancel → restart replay',
        'required {item.required ? "yes" : "no"} · observed {item.observed ? "yes" : "no"} · count {item.count ?? 0}',
        'proof {item.provenance_summary || item.provenance_level || "—"}',
        'proof chain {item.proof_chain_summary || "—"}',
        'item.proof_chain.slice(-3).map((chainEvent, chainIdx) => (',
        '{chainEvent.timestamp || "—"} · {chainEvent.event_type || "unknown"} · {chainEvent.provenance_level || "unknown"}',
        'evidence ts {typeof item.evidence?.timestamp === "string" ? item.evidence.timestamp : "—"}',
        'evidence source {typeof item.evidence?.source === "string" ? item.evidence.source : (typeof item.evidence?.operator_next_artifact === "string" ? item.evidence.operator_next_artifact : "—")}',
        'Venue-specific closure lanes',
        'venue lanes summary {reconciliationLifecycleContract?.venue_lanes_summary || "—"}',
        'reconciliationVenueLanes.length > 0 ? reconciliationVenueLanes.map((lane, idx) => (',
        'Binance / OKX lane 要分開看 baseline、path artifact、restart replay，避免 proof chain 被混成單一 closure 敘事。',
        'baseline {lane.baseline_observed ?? 0}/{lane.baseline_required ?? 0} · path {lane.path_observed ?? 0}/{lane.path_expected ?? 0} · replay {lane.restart_replay_status || "—"}',
        'next artifact {lane.operator_next_artifact || "—"}',
        'operator action {lane.operator_action_summary || "—"}',
        'remediation {lane.remediation_priority || "—"} · {lane.remediation_focus || "—"}',
        'provenance venue-backed {lane.provenance_counts?.venue_backed ?? 0} · dry-run {lane.provenance_counts?.dry_run_only ?? 0} · internal {lane.provenance_counts?.internal_only ?? 0} · missing {lane.provenance_counts?.missing_or_not_applicable ?? 0}',
        'missing required {(lane.missing_required_artifacts || []).join(" / ") || "none"}',
        'lane drilldown {lane.artifact_drilldown_summary || "—"}',
        'lane timeline {lane.timeline_summary || `timeline ${lane.timeline_count ?? 0} events · latest none`}',
        'operator instruction {lane.operator_instruction || "—"}',
        'verify {lane.verify_instruction || "—"}',
        'next check {lane.operator_next_check || "—"}',
        'lane artifacts {(lane.artifacts || []).slice(0, 3).map((artifact) => `${artifact.key || "unknown"}:${artifact.status || "unknown"}:${artifact.provenance_level || "unknown"}`).join(" · ") || "none"}',
        '(lane.timeline_events || []).slice(-3).map((event, eventIdx) => (',
        'lane timeline events none',
        'lifecycle contract summary {reconciliationLifecycleContract?.summary || "—"}',
        '倉位明細',
        'Open orders 明細',
        'Lifecycle event timeline',
        'timeline status {reconciliationTimeline?.status || "available"} · total events {reconciliationTimeline?.total_events ?? reconciliationTimelineEvents.length}',
        'latest event {reconciliationTimeline?.latest_event?.event_type || "—"} · {reconciliationTimeline?.latest_event?.order_state || "—"}',
        '最近委託正規化回放',
        'runtime truth {accountDegraded ? "degraded" : "fresh"}',
        'requested → normalized → contract',
        'readRecordString(position, ["symbol", "instId", "market", "pair"])',
        'readRecordNumber(order, ["amount", "qty", "size", "origQty", "sz"])',
        '最近拒單',
        '最近失敗',
        '最近委託',
        'Execution 狀態面板',
    ]
    for snippet in required_snippets:
        assert snippet in source


def test_signal_banner_declares_dashboard_as_canonical_execution_route_until_upgraded():
    source = _read("components/SignalBanner.tsx")
    required_snippets = [
        'SignalBanner 目前只提供快捷下單 / 自動交易切換；完整 Execution 狀態面板、Guardrail context 與 stale governance 仍以 Dashboard 為 canonical execution route。',
        '前往 Dashboard 檢查完整 Execution 狀態 →',
        'href="/"',
        'fetch("/api/trade", {',
        'fetch("/api/automation/toggle", {',
        'fetch("/api/predict/confidence")',
        'const deploymentBlockerDetails = runtimeDecision?.deployment_blocker_details ?? null;',
        'const breakerRecentWindow = deploymentBlockerDetails?.recent_window ?? null;',
        'const breakerRelease = deploymentBlockerDetails?.release_condition ?? null;',
        'const circuitBreakerActive = runtimeDecision?.deployment_blocker === "circuit_breaker_active";',
        'runtime closure {runtimeDecision.runtime_closure_state || "—"}',
        'circuit breaker：recent 50 release window',
        '不要把 support / component patch 當成 breaker release 替代品。',
        'SignalBanner 只同步 release math，不可把這裡的快捷面板誤讀成 deployment readiness。',
        'raw reason {runtimeDecision.allowed_layers_raw_reason || "—"}',
        'final reason {runtimeDecision.allowed_layers_reason || "—"}',
        'capacity opened but signal still HOLD',
        'patch active but execution still blocked',
    ]
    for snippet in required_snippets:
        assert snippet in source


def test_confidence_indicator_distinguishes_capacity_opened_vs_patch_blocked_states():
    source = _read("components/ConfidenceIndicator.tsx")
    required_snippets = [
        'const q15PatchExecutionBlocked = Boolean(',
        'const q15PatchCapacityOpened = Boolean(',
        'const breakerRecentWindow = deploymentBlockerDetails?.recent_window ?? null;',
        'const breakerRelease = deploymentBlockerDetails?.release_condition ?? null;',
        'const circuitBreakerActive = deploymentBlocker === "circuit_breaker_active";',
        'recent 50 release window',
        '至少還差 {breakerWinsGap ?? "—"} 勝',
        '不要把 support / component patch 當成 breaker release 替代品。',
        'capacity opened but signal still HOLD',
        'patch active 只證明 runtime floor-cross 元件已落地，不等於目前可部署',
        'q15 patch 已經吃到 current live row，但 execution 仍被 exact live bucket blocker / guardrail 壓住',
    ]
    for snippet in required_snippets:
        assert snippet in source


def test_strategy_lab_keeps_decision_quality_summary_surfaces():
    source = _read("pages/StrategyLab.tsx")
    required_snippets = [
        'avg_decision_quality_score',
        'avg_expected_drawdown_penalty',
        'avg_expected_time_underwater',
        'avg_allowed_layers',
        'primary_sleeve_key?: string;',
        'primary_sleeve_label?: string;',
        'sleeve_keys?: string[];',
        'sleeve_labels?: string[];',
        'const [strategySleeveFilter, setStrategySleeveFilter] = useState<string>("all");',
        'const strategyPrimarySleeveKey = (entry: StrategyEntry) => entry.metadata?.primary_sleeve_key || "uncategorized";',
        'const sleeveFilteredStrategies = useMemo(() => {',
        '多 sleeve 結構',
        'strategy.metadata?.primary_sleeve_label || "未分類 sleeve"',
        'strategy.metadata?.sleeve_labels?.join(" · ") || "單一路徑"',
        'activeSortSemantics',
        'selectedStrategy?.decision_contract',
        '⚠️ canonical DQ 缺失，暫退回 legacy ROI',
        'Decision Quality',
        'DQ {formatDecimal(activeResult?.avg_decision_quality_score, 3)}',
        'const { data: runtimeStatus } = useApi<StrategyLabRuntimeStatusResponse>("/api/status", 60000);',
        'const { data: liveDecisionStatus } = useApi<StrategyLabLiveDecisionResponse>("/api/predict/confidence", 60000);',
        'const executionReconciliation = runtimeStatus?.execution_reconciliation ?? null;',
        'const executionSurfaceContract = runtimeStatus?.execution_surface_contract ?? null;',
        'const executionOperationsSurface = executionSurfaceContract?.operations_surface ?? null;',
        'const executionDiagnosticsSurface = executionSurfaceContract?.diagnostics_surface ?? null;',
        'const metadataSmoke = runtimeStatus?.execution_metadata_smoke ?? null;',
        'const lifecycleAudit = executionReconciliation?.lifecycle_audit ?? null;',
        'const lifecycleContract = executionReconciliation?.lifecycle_contract ?? null;',
        'const lifecycleArtifactChecklist = Array.isArray(lifecycleContract?.artifact_checklist)',
        'const lifecycleVenueLanes = Array.isArray(lifecycleContract?.venue_lanes)',
        'const recoveryState = executionReconciliation?.recovery_state ?? null;',
        'const lifecycleChecklistTone = (status?: string | null) => {',
        'Execution runtime blocker sync',
        '目前 canonical execution route 仍在 Dashboard；Strategy Lab 這裡只同步 runtime blocker，避免回測語義與 execution 現況脫鉤。',
        'Lifecycle / replay',
        'Restart replay / recovery state',
        'restart replay {lifecycleAudit?.restart_replay_required ? "required" : "not-required"}',
        'baseline contract {lifecycleContract?.baseline_contract_status || "—"}',
        'replay verdict {lifecycleContract?.replay_verdict || "—"}',
        'artifact coverage {lifecycleContract?.artifact_coverage || "—"}',
        'Lifecycle event timeline {lifecycleTimeline?.status || "absent"} · total events {lifecycleTimeline?.total_events ?? 0}',
        'latest event {lifecycleTimeline?.latest_event?.event_type || "—"} · {lifecycleTimeline?.latest_event?.order_state || "—"}',
        'Artifact checklist / per-order closure',
        'artifact checklist summary {lifecycleContract?.artifact_checklist_summary || "—"}',
        'artifact provenance {lifecycleContract?.artifact_provenance_summary || "—"}',
        '逐筆 order artifact 對帳：validation → ack → trade history → partial fill / cancel → restart replay',
        'required {item.required ? "yes" : "no"} · observed {item.observed ? "yes" : "no"} · count {item.count ?? 0}',
        'proof {item.provenance_summary || item.provenance_level || "—"}',
        'proof chain {item.proof_chain_summary || "—"}',
        'item.proof_chain.slice(-3).map((chainEvent, chainIdx) => (',
        '{chainEvent.timestamp || "—"} · {chainEvent.event_type || "unknown"} · {chainEvent.provenance_level || "unknown"}',
        'Venue-specific closure lanes',
        'venue lanes summary {lifecycleContract?.venue_lanes_summary || "—"}',
        'lifecycleVenueLanes.length > 0 ? lifecycleVenueLanes.map((lane, idx) => (',
        'Binance / OKX lane 必須分開看 baseline、path artifact、restart replay，不能再把 mixed timeline 當成單一 closure 敘事。',
        'baseline {lane.baseline_observed ?? 0}/{lane.baseline_required ?? 0} · path {lane.path_observed ?? 0}/{lane.path_expected ?? 0} · replay {lane.restart_replay_status || "—"}',
        'next artifact {lane.operator_next_artifact || "—"}',
        'operator action {lane.operator_action_summary || "—"}',
        'remediation {lane.remediation_priority || "—"} · {lane.remediation_focus || "—"}',
        'provenance venue-backed {lane.provenance_counts?.venue_backed ?? 0} · dry-run {lane.provenance_counts?.dry_run_only ?? 0} · internal {lane.provenance_counts?.internal_only ?? 0} · missing {lane.provenance_counts?.missing_or_not_applicable ?? 0}',
        'missing required {(lane.missing_required_artifacts || []).join(" / ") || "none"}',
        'lane drilldown {lane.artifact_drilldown_summary || "—"}',
        'lane timeline {lane.timeline_summary || `timeline ${lane.timeline_count ?? 0} events · latest none`}',
        'operator instruction {lane.operator_instruction || "—"}',
        'verify {lane.verify_instruction || "—"}',
        'next check {lane.operator_next_check || "—"}',
        'lane artifacts {(lane.artifacts || []).slice(0, 3).map((artifact) => `${artifact.key || "unknown"}:${artifact.status || "unknown"}:${artifact.provenance_level || "unknown"}`).join(" · ") || "none"}',
        '(lane.timeline_events || []).slice(-3).map((event, eventIdx) => (',
        'lane timeline events none',
        'canonical surface {executionSurfaceContract?.canonical_surface_label || "Dashboard / Execution 狀態面板"}',

        'lifecycle contract summary {lifecycleContract?.summary || "—"}',
        'missing lifecycle events {(lifecycleContract?.missing_event_types || []).join(" / ") || "none"}',
        'live blocker',
        'live q15 closure',
        'const liveRuntimeClosureState = liveDecisionStatus?.runtime_closure_state ?? liveRuntimeTruth?.runtime_closure_state ?? null;',
        'const liveRuntimeClosureSummary = liveDecisionStatus?.runtime_closure_summary ?? liveRuntimeTruth?.runtime_closure_summary ?? null;',
        'const liveRouting = liveRuntimeTruth?.sleeve_routing ?? null;',
        'const liveActiveSleeves = Array.isArray(liveRouting?.active_sleeves) ? liveRouting.active_sleeves : [];',
        'const liveInactiveSleeves = Array.isArray(liveRouting?.inactive_sleeves) ? liveRouting.inactive_sleeves : [];',
        '當前 regime',
        'active sleeves',
        'inactive sleeves',
        'liveRouting?.active_ratio_text || "0/0"',
        'liveRouting?.current_regime || liveDecisionStatus?.regime_label || "—"',
        'liveRouting?.current_regime_gate || liveDecisionStatus?.regime_gate || "—"',
        'liveRouting?.current_structure_bucket || liveDecisionStatus?.current_live_structure_bucket || "—"',
        'liveActiveSleeves.map((item) => (',
        'liveInactiveSleeves.map((item) => (',
        '{item.label || item.key}',
        '{item.why || "—"}',
        'Execution Console 現在直接消費同一份 runtime sleeve routing；Strategy Lab 這裡只同步 activation truth，實際營運請前往 Execution Console。',
        'canonical surface {executionDiagnosticsSurface?.label || "Dashboard / Execution 狀態面板"}',
        '前往 Execution Console 檢查 active sleeves →',
        'const liveRecentPathologyApplied = Boolean(',
        'const liveRecentPathologyReason =',
        'const liveRecentPathologyWindow =',
        'const liveRecentPathologyAlerts =',
        'const liveRecentPathologySummary =',
        'const liveDeploymentBlockerDetails = liveDecisionStatus?.deployment_blocker_details ?? null;',
        'const breakerRecentWindow = liveDeploymentBlockerDetails?.recent_window ?? null;',
        'const breakerRelease = liveDeploymentBlockerDetails?.release_condition ?? null;',
        'const circuitBreakerActive = liveDecisionStatus?.deployment_blocker === "circuit_breaker_active";',
        'support route {liveDecisionStatus?.support_route_verdict || "—"}',
        'runtime closure {liveRuntimeClosureState || "unknown"}',
        'q15 runtime closure 狀態',
        'signal {liveDecisionStatus?.signal || "—"}',
        'layers {liveDecisionStatus?.allowed_layers_raw ?? "—"} → {liveDecisionStatus?.allowed_layers ?? "—"}',
        'patch {liveDecisionStatus?.q15_exact_supported_component_patch_applied ? "active" : "inactive"}',
        'runtime closure {liveRuntimeClosureState || "—"} · summary {liveRuntimeClosureSummary || "尚未取得 runtime closure summary。"}',
        'recent 50 release window',
        '至少還差 {breakerWinsGap ?? "—"} 勝',
        '目前主 blocker 是 recent win rate，不是 q15 patch。',
        '不要把 support / component patch 當成 breaker release 替代品。',
        '目前 canonical live path 仍被 circuit breaker 擋下；這個狀態優先於 q15 support / component patch，Strategy Lab 只應同步 release math，不可包裝成 deployment readiness。',
        'Recent distribution pathology',
        'window {liveRecentPathologyWindow ?? "—"} rows',
        'reason {liveRecentPathologyReason || "—"}',
        'alerts {(liveRecentPathologyAlerts || []).join(" / ") || "none"}',
        '這代表最近 canonical 決策樣本正在退化；Strategy Lab 只能同步這個 drift 事實，不能把局部回測亮點誤讀成 live deployment capacity。',
        'support alignment',
        'runtime exact support',
        'calibration exact lane',
        'runtime 已有',
        '目前已是 support-ready + patch active，但 signal 仍是 HOLD；這代表 runtime 已開出 1 層 deployment capacity，不等於自動進場。',
        '目前 q15 patch 已套用到 current live row，但 execution 仍被 exact live bucket blocker / guardrail 擋住；這裡要讀成 patch active but execution still blocked。',
        'gap to minimum {liveDecisionStatus?.support_progress?.gap_to_minimum ?? "—"}',
        'best single component {liveDecisionStatus?.best_single_component || "—"}',
        'Metadata smoke',
        '前往 Dashboard 檢查 execution runtime →',
    ]
    for snippet in required_snippets:
        assert snippet in source


def test_candlestick_chart_uses_stable_empty_prop_defaults_to_avoid_render_loops():
    source = _read("components/CandlestickChart.tsx")
    required_snippets = [
        'const EMPTY_TRADE_MARKERS: TradeMarkerInput[] = [];',
        'const EMPTY_EQUITY_CURVE: EquityPoint[] = [];',
        'const EMPTY_SCORE_SERIES: ScorePoint[] = [];',
        'tradeMarkers = EMPTY_TRADE_MARKERS,',
        'equityCurve = EMPTY_EQUITY_CURVE,',
        'scoreSeries = EMPTY_SCORE_SERIES,',
    ]
    for snippet in required_snippets:
        assert snippet in source


def test_fetch_api_formats_structured_reject_payloads_for_trade_guardrails():
    source = _read("hooks/useApi.ts")
    required_snippets = [
        'function formatApiErrorDetail(detail: unknown): string {',
        'const code = typeof payload.code === "string" ? payload.code : null;',
        'const message = typeof payload.message === "string" ? payload.message : null;',
        'return [code ? `[${code}]` : null, message].filter(Boolean).join(" ");',
        'throw new Error(formatApiErrorDetail(err.detail ?? err) || `${resp.status}`);',
    ]
    for snippet in required_snippets:
        assert snippet in source
